#!/usr/bin/env python3
"""DEPRECATED for Home glyphs as of v73 — use gen_remarkable_glyphs.py instead.

Legacy packer for GenerateImage SF-style filled glyphs → 1-bit bitmaps.
v73+ Home icons are hand-authored reMarkable strokes via gen_remarkable_glyphs.py.
"""
from __future__ import annotations

from pathlib import Path

from PIL import Image, ImageDraw, ImageFilter, ImageOps

ROOT = Path(__file__).resolve().parent
SRC = ROOT / "home_glyphs"
OUT_INC = ROOT.parent / "components/pocket_ui/src/home_glyphs.inc"

SIZE = 96  # source detail; Home draws at ~68% of tile via majority downsample
PAD_FRAC = 0.08
THRESH = 140  # JPEG gray halo → white unless clearly ink
NAMES = [
    ("notes", "Notes"),
    ("ledger", "Ledger"),
    ("clock", "Clock"),
    ("pass", "Pass"),
    ("weather", "Weather"),
    ("music", "Music"),
    ("settings", "Settings"),
    ("update", "Update"),
    ("reading", "Reading"),
]


def to_ink_mask(img: Image.Image) -> Image.Image:
    g = ImageOps.grayscale(img)
    # Slight blur then threshold so JPEG ringing doesn't speckle.
    g = g.filter(ImageFilter.MedianFilter(size=3))
    bw = g.point(lambda p: 0 if p < THRESH else 255, mode="L")
    return bw


def crop_pad_square(bw: Image.Image) -> Image.Image:
    bbox = bw.point(lambda p: 255 - p).getbbox()  # ink bbox (black=0)
    if not bbox:
        return Image.new("L", (SIZE, SIZE), 255)
    x0, y0, x1, y1 = bbox
    w, h = x1 - x0, y1 - y0
    pad = max(2, int(round(max(w, h) * PAD_FRAC)))
    x0 = max(0, x0 - pad)
    y0 = max(0, y0 - pad)
    x1 = min(bw.width, x1 + pad)
    y1 = min(bw.height, y1 + pad)
    crop = bw.crop((x0, y0, x1, y1))
    side = max(crop.width, crop.height)
    square = Image.new("L", (side, side), 255)
    ox = (side - crop.width) // 2
    oy = (side - crop.height) // 2
    square.paste(crop, (ox, oy))
    return square


def area_downsample(bw: Image.Image, size: int) -> Image.Image:
    """Majority-vote downsample — keeps filled silhouettes, kills 1px junk."""
    src = bw.resize((size * 4, size * 4), Image.Resampling.NEAREST)
    # BOX average then hard threshold.
    small = src.resize((size, size), Image.Resampling.BOX)
    return small.point(lambda p: 0 if p < 160 else 255, mode="L")


def cleanup(mask: Image.Image) -> Image.Image:
    """Drop isolated ink pixels; fill 1-pixel holes."""
    px = mask.load()
    w, h = mask.size
    out = mask.copy()
    opx = out.load()
    for y in range(h):
        for x in range(w):
            ink = px[x, y] < 128
            n = 0
            for dy in (-1, 0, 1):
                for dx in (-1, 0, 1):
                    if dx == 0 and dy == 0:
                        continue
                    xx, yy = x + dx, y + dy
                    if 0 <= xx < w and 0 <= yy < h and px[xx, yy] < 128:
                        n += 1
            if ink and n <= 1:
                opx[x, y] = 255
            elif (not ink) and n >= 7:
                opx[x, y] = 0
    return out


def pack_bits(mask: Image.Image) -> list[int]:
    w, h = mask.size
    row_bytes = (w + 7) // 8
    bits = [0] * (row_bytes * h)
    px = mask.load()
    for y in range(h):
        for x in range(w):
            if px[x, y] < 128:
                bits[y * row_bytes + (x >> 3)] |= 1 << (7 - (x & 7))
    return bits


def emit_c(arrays: list[tuple[str, list[int]]]) -> str:
    row_bytes = (SIZE + 7) // 8
    lines = [
        "// Auto-generated 1-bit Home glyphs (v71). Do not edit by hand.",
        f"// {SIZE}×{SIZE}, MSB packed, 1 = ink. Regenerated by tools/pack_home_glyphs.py",
        f"static constexpr int kHomeGlyphSize = {SIZE};",
        f"static constexpr int kHomeGlyphRowBytes = {row_bytes};",
        f"static constexpr int kHomeGlyphBytes = {SIZE * row_bytes};",
        "",
    ]
    for ident, bits in arrays:
        lines.append(f"static const uint8_t kGlyph{ident}[kHomeGlyphBytes] = {{")
        for i in range(0, len(bits), 12):
            chunk = ", ".join(f"0x{b:02X}" for b in bits[i : i + 12])
            comma = "," if i + 12 < len(bits) else ""
            lines.append(f"  {chunk}{comma}")
        lines.append("};")
        lines.append("")
    lines.append("static const uint8_t* kHomeGlyphBits[9] = {")
    for ident, _ in arrays:
        lines.append(f"  kGlyph{ident},")
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    arrays = []
    thumbs = []
    for slug, ident in NAMES:
        path = SRC / f"glyph-{slug}.jpg"
        if not path.exists():
            path = SRC / f"glyph-{slug}.png"
        img = Image.open(path).convert("RGB")
        bw = to_ink_mask(img)
        square = crop_pad_square(bw)
        mask = cleanup(area_downsample(square, SIZE))
        ink = sum(1 for p in mask.getdata() if p < 128)
        frac = ink / (SIZE * SIZE)
        if not (0.12 <= frac <= 0.62):
            raise SystemExit(f"{slug}: ink fraction {frac:.3f} out of range (blob/empty)")
        bits = pack_bits(mask)
        arrays.append((ident, bits))
        mask.save(SRC / f"1bit-{slug}.png")
        thumbs.append(mask)
        print(f"{slug:10s} ink={ink:4d} ({frac*100:4.1f}%)")

    OUT_INC.write_text(emit_c(arrays))
    print(f"wrote {OUT_INC}")

    # 4× preview sheet
    scale = 4
    cell = SIZE * scale + 24
    sheet = Image.new("L", (3 * cell, 3 * cell), 255)
    draw = ImageDraw.Draw(sheet)
    for i, mask in enumerate(thumbs):
        big = mask.resize((SIZE * scale, SIZE * scale), Image.Resampling.NEAREST)
        col, row = i % 3, i // 3
        x = col * cell + 12
        y = row * cell + 12
        sheet.paste(big, (x, y))
        draw.rectangle([x - 1, y - 1, x + SIZE * scale, y + SIZE * scale], outline=180)
    preview = SRC / "preview-1bit.png"
    sheet.save(preview)
    print(f"wrote {preview}")


if __name__ == "__main__":
    main()
